### ISSUE TITLE
Allow y3 rotations

### ISSUE THREAD

**Issue by ghost** [tdecker91/visualcube#10]
I believe that your regular expressions don't parse rotations such as y3, which is permitted in the original VisualCube. This isn't necessary, of course, given that the user can just supply y' instead, but I've found some algorithms (erroneously) written with three rotations and it would be nice to just have extra flexibility with your script instead of replacing the strings globally. Thanks for your consideration!

**Comment by tdecker91** [comment]
@OtterCuber Thanks for the feedback. I didn't realize the original VisualCube supported this. I didn't see a problem supporting this so I have made a change and published version 1.0.13 to [github](https://github.com/tdecker91/visualcube/releases/tag/v1.0.13) and [npm](https://www.npmjs.com/package/sr-visualizer/v/1.0.13)

Comparing the two, it still works a bit different from the original. For example the original interprets "y4" as just "y", (when technically it would be y0) but now this version will interpret that correctly as "y4" and perform no move on the cube. I was debating making it work exactly like the original but decided I liked this better as it is how I would expect it to work if moves like "y3" also work. 

If you're interested you can check out my new project https://github.com/tdecker91/puzzle-gen 
It's inspired by visualcube and supports rendering different puzzles.
