### ISSUE TITLE
Add advanced F2L to solvingrubik.com

### ISSUE THREAD

**Issue by haulin** [tdecker91/visualcube#2]
Don't know where else to ask this, but would it be possible to add "advanced F2L" cases to the website?

I am trying to memorize the 12 cases presented in this video: https://www.youtube.com/watch?v=3B_oB2YrLvk
The pinned comment has timestamps, but it would be much nicer to have them all in one page.

I could help if the website's source is open as well.

**Comment by tdecker91** [comment]
@haulin wow I’m surprised anyone is actually using that site and finding it helpful. Haha 😃 that was one of the first websites I made and I haven’t touched it in ages. It sure could use some love. I never got around to adding everything I wanted to. 

I’d be happy to add some additional f2l cases. Maybe on a weekend when I get some time. I’ll have to see if I can dig up the source somewhere and figure out how to deploy it again 😂

**Comment by haulin** [comment]
I am fairly new to cubing and don't know what the best resources are. I wanted to create a visualisation for myself, which made me search for this library. And then I saw the website, which is pretty much what I was after. Looks really clean. Just misses the occasional case here and there.

**Comment by tdecker91** [comment]
I’ve shut down the site and I’m closing this issue. Sorry I never got around to it
