### ISSUE TITLE
Cannot import Masking

### ISSUE THREAD

**Issue by sschellhoff** [tdecker91/visualcube#3]
Hey,
i try to create a simple app for myself to keep practice my algorithms. I go for a Ionic/vue3 stack with typescript. I try to use the Masking enum you have in your lib but i get runtime errors. So some example code is this:
```
import SRVisualizer, {CubeOptions, Masking} from "sr-visualizer";

export function createF2L(algorithm: string): CubeOptions {
    return {
        cubeSize: 3,
        width: 500,
        height: 500,
        algorithm: algorithm,
        mask: Masking.F2L
    };
}

export function createELL(algorithm: string): CubeOptions {
    return {
        cubeSize: 3,
        width: 500,
        height: 500,
        algorithm: algorithm,
        mask: SRVisualizer.Masking.ELL
    };
}
```
At runtime, SRVisualizer and Masking are both undefined. What i could do is:
`mask: "f2l" as Masking.F2L`

but the reason i use typescript is typesafety so doing this is a nogo.

I am not sure why this is the case. Do you have any clue? Am i the only one with this problem?

Greetings

**Comment by tdecker91** [comment]
@sschellhoff Hey, thanks for the input. Sorry for the late reply. Have you already discovered a work around?

It looks like I may not be bundling the module correctly. I am working on fixing my bundling and typing so it can be used properly as described in the README.

in the meantime you can use `import {cubePNG} from "sr-visualizer";`  to import the method. Masking and other constants still aren't importable. I'll update this thread when I publish a new version. Sorry for the inconvenience

**Comment by tdecker91** [comment]
@sschellhoff Good news, I was able to fix the typing issue. Types are now generated with the typescript build. 

This is present in version 1.0.9 published to npm. 

There is no default export. If you want to import the module as a whole, you `import *` with an alias like this.
```typescript
import * as SRVisualizer from 'sr-visualizer'
```

and you can access values  like
```typescript
SRVisualizer.cubePNG(...)
SRVisualizer.Masking.F2L
```

Or you can destructure and grab just what you want

```typescript
import { cubePNG, Masking, ICubeOptions } from 'sr-visualizer'
```

I hope this helps. Let me know if you run into anything else.
