### ISSUE TITLE
Change Masked Color

### ISSUE THREAD

**Issue by ThisTemba** [tdecker91/visualcube#4]
This is a really great library @tdecker91 . I wonder, if it's not too much work, if it would be possible to allow for custom masked colors? It seems like the color of the cube, background and facelets can be set, but the "mask color" is fixed as a dark gray.

![image](https://user-images.githubusercontent.com/36087610/130333519-51731502-b685-4cea-8990-fe884217e054.png)

Thanks,

**Comment by tdecker91** [comment]
@ThisTemba Great suggestion. Yeah that should be no problem.

**Comment by tdecker91** [comment]
@ThisTemba 

With version [`1.0.11`](https://www.npmjs.com/package/sr-visualizer/v/1.0.11) you can now include `maskColor` option to override the color that masked stickers are drawn with. You can use HTML color names or color codes like the other color options.

## Example 1
![download-1](https://user-images.githubusercontent.com/3656030/130733218-392a7a99-baaf-43d7-a939-83eae0204e05.png)
```javascript
cubePNG(element, {
    view: 'plan',
    mask: Masking.OLL,
    maskColor: 'white',
    case: "F R' F' R U R U' R'",
  });
```

## Example 2
![download-2](https://user-images.githubusercontent.com/3656030/130733229-818e0c25-001c-4d34-b58f-23838762d73b.png)
```javascript
cubePNG(element, {
    view: 'plan',
    mask: Masking.OLL,
    maskColor: '#AAF',
    case: "F R' F' R U R U' R'",
  });
```
