### ISSUE TITLE
Behavioral differences about algorithms

### ISSUE THREAD

**Issue by roudai** [tdecker91/visualcube#7]
For example, when the algorithm is set to F'2, the original VIsualCube is two rotations of F', but the last "2" are ignored and the operation becomes F'.

**Comment by tdecker91** [comment]
@roudai Thanks for the feedback. I was able to add options to the algorithm parser to function more like the original version
check version `1.0.12`

also, here is a shameless plug for the successor to this library https://github.com/tdecker91/puzzle-gen  Check it out if you'd like. Should work better than this one and has more features 😄
